* Desafio da Carga Útil de Marte
NAME          MARS_ROVER
ROWS
 N  OBJ_VALOR
 L  MASSA_KG
 L  VOLUME_M3
 L  ENERGIA_W
 L  COMPAT
COLUMNS
    X_ESPEC   OBJ_VALOR   50.0      MASSA_KG    12.0
    X_ESPEC   VOLUME_M3   15.0      ENERGIA_W   10.0
    X_MAGN    OBJ_VALOR   45.0      MASSA_KG    8.0
    X_MAGN    VOLUME_M3   10.0      ENERGIA_W   8.0
    X_PERF    OBJ_VALOR   80.0      MASSA_KG    25.0
    X_PERF    VOLUME_M3   30.0      ENERGIA_W   20.0
    X_PERF    COMPAT      1.0
    X_CLIMA   OBJ_VALOR   35.0      MASSA_KG    5.0
    X_CLIMA   VOLUME_M3   5.0       ENERGIA_W   5.0
    X_BRACO   OBJ_VALOR   60.0      MASSA_KG    18.0
    X_BRACO   VOLUME_M3   25.0      ENERGIA_W   15.0
    X_LABQUIM OBJ_VALOR   95.0      MASSA_KG    30.0
    X_LABQUIM VOLUME_M3   40.0      ENERGIA_W   25.0
    X_LABQUIM COMPAT      1.0
    X_SENSORUV OBJ_VALOR  40.0      MASSA_KG    4.0
    X_SENSORUV VOLUME_M3  3.0       ENERGIA_W   6.0
    X_RADAR   OBJ_VALOR   75.0      MASSA_KG    22.0
    X_RADAR   VOLUME_M3   20.0      ENERGIA_W   18.0
    X_PAINELXL OBJ_VALOR  110.0     MASSA_KG    35.0
    X_PAINELXL VOLUME_M3  50.0      ENERGIA_W   -30.0
    X_ANTENA  OBJ_VALOR   25.0      MASSA_KG    6.0
    X_ANTENA  VOLUME_M3   8.0       ENERGIA_W   4.0
    X_TERMO   OBJ_VALOR   15.0      MASSA_KG    2.0
    X_TERMO   VOLUME_M3   2.0       ENERGIA_W   1.0
    X_METANO  OBJ_VALOR   55.0      MASSA_KG    7.0
    X_METANO  VOLUME_M3   8.0       ENERGIA_W   9.0
    X_RTG     OBJ_VALOR   120.0     MASSA_KG    40.0
    X_RTG     VOLUME_M3   35.0      ENERGIA_W   -80.0
    X_CAMPAN  OBJ_VALOR   65.0      MASSA_KG    15.0
    X_CAMPAN  VOLUME_M3   12.0      ENERGIA_W   12.0
    X_MICRO   OBJ_VALOR   30.0      MASSA_KG    9.0
    X_MICRO   VOLUME_M3   7.0       ENERGIA_W   5.0
    X_COLETOR OBJ_VALOR   85.0      MASSA_KG    28.0
    X_COLETOR VOLUME_M3   25.0      ENERGIA_W   20.0
    X_COLETOR COMPAT      -1.0
    X_BATERIA OBJ_VALOR   40.0      MASSA_KG    15.0
    X_BATERIA VOLUME_M3   10.0      ENERGIA_W   20.0
    X_RODA    OBJ_VALOR   20.0      MASSA_KG    10.0
    X_RODA    VOLUME_M3   25.0      ENERGIA_W   2.0
    X_COMP    OBJ_VALOR   90.0      MASSA_KG    13.0
    X_COMP    VOLUME_M3   10.0      ENERGIA_W   22.0
    X_ESCUDO  OBJ_VALOR   50.0      MASSA_KG    16.0
    X_ESCUDO  VOLUME_M3   20.0      ENERGIA_W   10.0
RHS
    RHS1      MASSA_KG    150.0
    RHS1      VOLUME_M3   200.0
    RHS1      ENERGIA_W   75.0
    RHS1      COMPAT      1.0
BOUNDS
 BV BND1      X_ESPEC
 BV BND1      X_MAGN
 BV BND1      X_PERF
 BV BND1      X_CLIMA
 BV BND1      X_BRACO
 BV BND1      X_LABQUIM
 BV BND1      X_SENSORUV
 BV BND1      X_RADAR
 BV BND1      X_PAINELXL
 BV BND1      X_ANTENA
 BV BND1      X_TERMO
 BV BND1      X_METANO
 BV BND1      X_RTG
 BV BND1      X_CAMPAN
 BV BND1      X_MICRO
 BV BND1      X_COLETOR
 BV BND1      X_BATERIA
 BV BND1      X_RODA
 BV BND1      X_COMP
 BV BND1      X_ESCUDO
ENDATA